config/routes.rb
SampleTwitterApp::Application.routes.draw do
  
 

  resources :users
  resources :sessions

  root to:  'static_pages#home'

  
  match "/signin"  , to: 'sessions#new'

  

 

 
  match "/help"    , to: 'static_pages#help'
  match "/contact" , to: 'static_pages#contact'
  match "/about"   , to: 'static_pages#about'
  match "/home"    , to: 'static_pages#home'
  match '/signout',  to: 'sessions#destroy', via: :delete
  match "/signup"  , to: 'users#new'
 match "/users"     , to: 'users#index'
 

 

 

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name,:password,:password_confirmation

  has_secure_password

  before_save {|user| user.email=user.email.downcase }
  


  
  VALID_EMAIL_REGEX=/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, 
  			presence: true,
  			uniqueness:{case_sensitive: false} ,
  			format: { with: VALID_EMAIL_REGEX, on: :create }

  validates :password,
  			     length: { minimum: 6 }
  validates :password_confirmation,
  		    	presence: true

  validates :name, presence: true,length: {maximum: 50}
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
   

  #Confirming the user is logged in or authorized to view the pages
 
 #protected so that sub classes can access them


 protected

    def current_user
      @current_user||=User.find(session[:user_id]) if session[:user_id]
      end
    
    helper_method :current_user 
  
  protected

    def current_user?(user)
        user==current_user
    end



  protected

  def confirm_user_logged_in
    unless current_user
      flash[:error]="Please login"
      redirect_to signin_path
      return false #halts the before_filter  
    else
      return true
    end
  end
  

  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


#------------------------------Start User Sign In-----------------------------

 
  def new
    @user=User.new

  end


#User Sign In
	def create 

		 
	 

			#Find user with email id
			@user=User.find_by_email(params[:session][:email])	
		 

				#  password validation
				if @user&&@user.authenticate(params[:session][:password])
					#storing session info
		 			session[:user_id]=@user.id
		 			session[:username]=@user.email
	 			 #Giving mesage of succesful login
					flash.now[:success]="Sign In Successful"
					   #directing to authorized pages
					redirect_to user_path(@user)
				else
					flash.now[:error]="Invalid password/email combination"
					render 'new'
				end	
		 	
		 
	end

#------------------------------End of  User Sign In-----------------------------

#------------------------------Start  of   User SignOut-----------------------------
	def destroy
		#storing session info
        session[:user_id]= nil
        session[:username]=nil
 
        flash[:success]=" Successfully logged out"
		redirect_to root_path
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
	 

  def home
  end

  def help
  end

  def about
  end


  def contact

  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
before_filter :confirm_user_logged_in,    :except => [:new,:create]
before_filter :correct_user,              :except => [:index,:listUsers,:new,:create,:show,:destroy]
 

 
 def index
   listUsers
    render 'listUsers'
 end

 def listUsers
    @users= User.paginate(page: params[:page],per_page: 20) 
 end

  

  def show
  	#raise params.inspect
	@user=User.find(params[:id])

  end

  def new
  @user= User.new
  end

  def create
    @user = User.new(params[:user])
      if @user.save
  
       #storing session info
      session[:user_id]=@user.id
      session[:username]=@user.email
       #Giving mesage of succesful login
      flash[:success]="Welcome #{@user.name}"

      
         #directing to authorized pages
      redirect_to user_path(@user)
     else
        flash[:warning]="User not created"
        redirect_to signup_path
      end
  end


  def edit
    @user= User.find_by_id(params[:id])

  end

  def update
      @user= User.find_by_id(params[:id])
      @user.update_attributes(params[:user])
       if @user.save
         flash[:success]="Successfully modified"
        redirect_to user_path(@user)
       else
        flash[:warning]="Sorry cannot be modified"
       render "edit"
     end

  end




  def destroy

    @user=User.find_by_id(params[:id])
    if @user.destroy
      flash[:success]="User #{@user.name} deleted successfully"
    else
      flash[:error]="Cannot delete #{@user.name}"
    end

       redirect_to users_path

  end

private

def correct_user
   @user= User.find_by_id(params[:id])
 
    unless current_user?(@user)
      redirect_to root_path 
      flash[:error]="Sorry !! You dont have access to the  page you have requested" 
   end
end



   

end

app/helpers/application_helper.rb
module ApplicationHelper


#Returns full title on a page per tilte basis
	def full_title(page_title)
		base_title="Lets Tweet"
	
		if page_title.empty?
			base_title
		else
			"#{base_title}|#{page_title}"
		end
	
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper


	#Returns the gravatar for the given user
	def gravatar_for (user)
		gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url="http://gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url,alt: user.name,class: "gravatar")
	end
end

app/views/integration_tests/authentication_pages.html.erb
<h1>IntegrationTests#authentication_pages</h1>
<p>Find me in app/views/integration_tests/authentication_pages.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="https://github.com/simita84/sampleTwitterApp">
		© Simi Tresa Antony</a>
	</small>
		<nav>
			<ul>
				<li><%=link_to "About",about_path%></li>
				<li><%=link_to "Contact",contact_path%></li>
				<li><%=link_to "Help",help_path%></li>
			</ul>
		</nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%=link_to "Tweet with Us",'#',id:"logo"%>
			<nav>
				<ul class="nav pull-right">
					<li><%=link_to "Home",   root_path %></li>
					<li><%=link_to "Help",   help_path %></li>
					
					 <!-- Check if signed in-->
					<%if current_user%>-->
					<li><%=link_to "Users",users_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account<b class="caret"></b>
						</a>
							<ul class="dropdown-menu" >
								<li><%=link_to "Profile",user_path(current_user)%></li>
								<li><%=link_to "Settings",edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%=link_to "Not #{current_user.name}? Sign Out",
										signout_path,method: "delete" %></li>
							</ul>
					</li>
					 <!-- Check if signed out-->
					<%else%>
						<li><%=link_to "Sign In",signin_path %></li>
					<%end%>
				</ul>
			</nav>
			</div>		
		</div>
	</header>
<div class="container">
	<%flash.each do |key,value|%>
		<div class='alert alert-<%=key%>'>
			<%=value%>
		</div>
	<%end%>
	<%= yield %>
	<%=render partial: "layouts/footer"%>

</div>
<%=debug(params)if Rails.env.development?%>
</body>
</html>

app/views/shared/_error_messages.html.erb
 
 
<% if @user.errors.any? %>

 
	<div id="error_explanation">
		<div class="alert alert-error">
		The form contains <%=pluralize(@user.errors.count,"error")%>
	</div>

	<ul>
		<% @user.errors.full_messages.each do |message|%>
			<li>*<%=message%></li>
		<%end%>
	</ul>
<%end%>
</div>

app/views/static_pages/about.html.erb
<%provide(:title,'About Us')%>


<body>
	<h1>About Us</h1>
</body>

 

app/views/static_pages/contact.html.erb
<%provide(:title,'Contact Us')%>


<body>
	<h1>Contact Us</h1>
</body>

 

app/views/static_pages/help.html.erb
<%provide(:title,'Help')%>
 

<body>
	<h1>Help</h1>
</body>


 

app/views/static_pages/home.html.erb
 
<%provide(:title,'Home') %>

 <div class="center hero-unit"> 
 	
		<h1 class="center">	
			<%=link_to image_tag("tweet_bird_right.jpeg",alt:"Tweet")%>
			Welcome to Tweeter
			<%=link_to image_tag("tweet_bird_left.jpeg",alt:"Tweet")%>
		</h1>
		
  <p>
  	This is a  Sample Tweetteer Application.
  	<br>
  	<%=link_to "Sign Up",signup_path, class: "btn btn-large btn-primary" %>
  
	</p>
		
		
 
  </div>
 
 

app/views/static_pages/login.html.erb
<%provide(:title,'Sign In') %>
 
<h1>Sign In</h1>
<div class="row">
	<div class="span6 offset 3">
		<div class="hero-unit">
					<%= render 'shared/error_messages'%> 
					
			<%= form_for @user, url: {controller:"access",action: "create"} do |f| %>
				<%=f.label :name%>
				<%=f.text_field :name%>
				<%=f.label :email%>
				<%=f.text_field :email%>
				<%=f.label :password%>
				<%=f.password_field :password%>
				<%=f.label :password_confirmation,"Confirmation"%>
				<%=f.password_field :password_confirmation%><br>
				<%=f.submit "Submit",class:"btn btn-large btn-primary"%>
			<% end %> 
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<div class="row">
	<div class="span6 offset 3">
		<div class="hero-unit">
					<%= render 'shared/error_messages'%> 
		
			<%= form_for(@user) do |f| %>
				<%=f.label :name%>
				<%=f.text_field :name%>
				<%=f.label :email%>
				<%=f.text_field :email%>
				<%=f.label :password%>
				<%=f.password_field :password%>
				<%=f.label :password_confirmation,"Confirmation"%>
				<%=f.password_field :password_confirmation%><br>
				<%=f.submit "Submit",class:"btn btn-large btn-primary"%>
		<% end %>

		</div>
	</div>
</div>

app/views/users/edit.html.erb
<%provide(:title,'Modify profile') %>
 
<h1>Modify profile</h1>
<div class="row">
	<div class="span 6 offset2">
			<%= render 'form' %> 
 
	</div>
</div>
 


 

app/views/users/index.html.erb
<%provide(:title,"Index")%>

app/views/users/listUsers.html.erb
<%provide(:title,"All Users")%>

<h1>All Users</h1>

<%=will_paginate%>
	<%@users.each do |user|%>
		<ul class="users">
			<li>

				<%=gravatar_for user%>
				<%=link_to user.name,user_path(user)%>
 
			 		<%unless user==current_user%>
						<%if current_user.admin?%>
							<div class="btn btn-danger"> 
								<%=link_to "Delete",user, method: :delete,
													   confirm: "Are you sure you want to delete #{user.name}?"
													    %>
					<%end%>
 
				
			
	<%end%>
		</li>
	</ul>
<%end%>
<%=will_paginate%>

app/views/users/new.html.erb
<%provide(:title,'Sign Up') %>
 
<h1>Sign Up</h1>
<div class="row">
	<div class="span 6 offset2">
			<%= render 'form' %> 
	</div>
</div>
 


 

app/views/users/show.html.erb
<%provide(:title,@user.name)%>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%=gravatar_for @user%>
				<%=@user.name%><br>
			</h1>
		</section>
	</aside>
</div>